version: '3'

services:
  web:
    build: web/
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@db:5432/db
      - SANDBOX_URL=http://sandbox:1337
    env_file:
      - web/.env
    depends_on:
      - db
      - sandbox
  sandbox:
    build: sandbox/
    privileged: true
    expose:
      - 1337
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD} # set this in your .env file
      - POSTGRES_DB=db
    expose:
      - 5432
