name: package test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Dev Env tests
      run: |
        python "test/dev_env_test.py"
        
    - name: Run Refinaid tests
      run: |
        python "test/action/load_df.py"
    
    - name: Finish tests
      run: |
        echo "All Tests are PASS!"
        